spring.application.name=seriestracker

# H2 tietokannan määritykset, konfiguraatiot
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/seriestracker;MODE=MySQL;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

# Näytä järjestelmän generoima SQL
#spring.jpa.show-sql=true

# Port
server.port=8090

# HTTPS
#spring.ssl.enabled=true
